#!/bin/bash
FROM --platform=linux/amd64 python:3.9

WORKDIR /src

COPY ./requirements.txt /src/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt

COPY ./ /src/database

CMD ["python", "-u" ,"-m" ,"database"]
